version: '3.8'

services:
  timescaledb:
    image: docker.io/timescale/timescaledb:latest-pg14
    container_name: timescaledb_ecg
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=ecg_data
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - timescale_data:/var/lib/postgresql/data
    restart: always

  python_app:
    build: ./app
    container_name: python_app
    depends_on:
      - timescaledb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ecg_data
      - POSTGRES_HOST=timescaledb
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - timescaledb
    restart: always

volumes:
  timescale_data:
  grafana_data:
